require: rubocop-rspec

Layout/AlignHash:
  EnforcedLastArgumentHashStyle: ignore_implicit

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/SpaceBeforeFirstArg:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - "*.gemspec"

Metrics/LineLength:
  Enabled: true
  Max: 125

Naming/FileName:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FormatString:
  EnforcedStyle: sprintf

Style/RegexpLiteral:
  EnforcedStyle: mixed

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Style/TrivialAccessors:
  AllowPredicates: true
  AllowDSLWriters: true
